#!/bin/bash

# Upload the ClinVar-GKM monthly FULL bundle from local disk to Cloudflare R2.
# Runs after export-gkm-dicts.sh + assemble-gkm-dicts.py have produced the bundle.
#
# As of Plan 4 the full bundle is published MONTH-END ONLY (retroactively, for the
# last release of a month). Weekly publishing moved to the delta product
# (upload-gkm-delta-to-r2.sh → deltas/). This script now manages only:
#   datasets/                       — monthly full bundles for the current year + 00-latest
#   datasets/parquet/{YYYY-MM}/     — per-section Parquet for each monthly full (dated)
#   datasets/parquet/00-latest/     — per-section Parquet for the newest monthly full
#   archives/{yyyy}/                — monthly bundles + parquet/{YYYY-MM}/ from prior years
#   README.txt                      — bucket overview
#
# The passed bundle is published UNCONDITIONALLY to the monthly slot. Boundary
# detection now governs only year-rollover archiving: if the newest monthly already
# in datasets/ is from a prior year, that year's monthly bundles AND its dated Parquet
# month sets are moved to archives/{yyyy}/ before the new upload. index.json is
# regenerated by generate-r2-index.sh.
#
# Usage:
#   ./upload-gkm-to-r2.sh <export_date> <dataset_version> <bundle_file> [--dry-run] [--parquet-dir=DIR]
#
# Examples:
#   ./upload-gkm-to-r2.sh 2026-06-27 v2_5_0 /tmp/clinvar-gkm-2026-06-27.json.gz
#   ./upload-gkm-to-r2.sh 2026-06-27 v2_5_0 /tmp/clinvar-gkm-2026-06-27.json.gz --dry-run

set -e

# --- Positional arguments ---
if [[ $# -lt 3 ]]; then
  echo "Usage: $0 <export_date> <dataset_version> <bundle_file> [--dry-run] [--parquet-dir=DIR]"
  echo "  export_date      ClinVar release date (YYYY-MM-DD)"
  echo "  dataset_version  Dataset version (e.g. v2_5_0)"
  echo "  bundle_file      Local path to the assembled bundle (.json.gz)"
  exit 1
fi

EXPORT_DATE="$1"
DATASET_VERSION="$2"
BUNDLE_FILE="$3"
shift 3

# Validate date format
if ! [[ "$EXPORT_DATE" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
  echo "ERROR: export_date must be YYYY-MM-DD format, got '${EXPORT_DATE}'"
  exit 1
fi

# --- Parse flags ---
DRY_RUN=false
PARQUET_DIR=""
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --parquet-dir=*) PARQUET_DIR="${arg#--parquet-dir=}" ;;
    *)
      echo "ERROR: Unknown argument '${arg}'"
      echo "Usage: $0 <export_date> <dataset_version> <bundle_file> [--dry-run] [--parquet-dir=DIR]"
      exit 1
      ;;
  esac
done

# --- R2 Configuration ---
R2_ACCOUNT_ID="09208aa33790838db213a21f630c33e7"
R2_BUCKET="clinvar-gkm"
R2_ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
R2_PROFILE="r2"
R2_PUBLIC_URL="https://pub-f0ad0e0dac0345408dcc95bda20beb42.r2.dev"

# --- Derived date components ---
YEAR="${EXPORT_DATE:0:4}"
MM="${EXPORT_DATE:5:2}"

# --- Filenames ---
MONTHLY_FILE="clinvar-gkm_${YEAR}-${MM}.json.gz"
LATEST_MONTHLY="clinvar-gkm_00-latest.json.gz"

# --- Locate script directory for r2-readme.txt + generate-r2-index.sh ---
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# =====================================================================
# Helper functions
# =====================================================================

r2_upload() {
  local src="$1" dest="$2" content_type="${3:-application/gzip}"
  if $DRY_RUN; then
    echo "  [dry-run] upload: ${dest}"
    return
  fi
  aws s3 cp "$src" "s3://${R2_BUCKET}/${dest}" \
    --endpoint-url "${R2_ENDPOINT}" \
    --profile "${R2_PROFILE}" \
    --content-type "${content_type}" \
    --quiet
}

r2_copy() {
  # Server-side (no-egress) copy that works across object sizes despite two R2 gaps:
  #   * multipart copy with default props calls GetObjectTagging (R2: NotImplemented)
  #   * single-part copy with --copy-props none/metadata-directive sends header
  #     x-amz-tagging-directive:REPLACE (R2: NotImplemented)
  # No single `aws s3 cp` mode covers both. So: large objects (>=2GB — i.e. the JSON
  # bundles) go via `aws s3 cp --copy-props none` (multipart, issues no tag calls);
  # everything smaller via `aws s3api copy-object` (a single CopyObject that sends
  # neither tag header — verified on small + ~1GB parquet; it is slow/capped near 5GB,
  # which is why bundles use the cp path instead).
  local src="$1" dest="$2"
  if $DRY_RUN; then
    echo "  [dry-run] copy: ${src} -> ${dest}"
    return
  fi
  local size
  size=$(aws s3api head-object --bucket "${R2_BUCKET}" --key "${src}" \
    --endpoint-url "${R2_ENDPOINT}" --profile "${R2_PROFILE}" \
    --query ContentLength --output text 2>/dev/null || echo 0)
  if [[ "${size}" -ge 2147483648 ]]; then
    aws s3 cp "s3://${R2_BUCKET}/${src}" "s3://${R2_BUCKET}/${dest}" \
      --endpoint-url "${R2_ENDPOINT}" --profile "${R2_PROFILE}" --copy-props none --quiet
  else
    aws s3api copy-object --bucket "${R2_BUCKET}" --key "${dest}" \
      --copy-source "${R2_BUCKET}/${src}" \
      --endpoint-url "${R2_ENDPOINT}" --profile "${R2_PROFILE}" >/dev/null
  fi
}

r2_ls() {
  local prefix="$1"
  aws s3 ls "s3://${R2_BUCKET}/${prefix}" \
    --endpoint-url "${R2_ENDPOINT}" \
    --profile "${R2_PROFILE}" \
    2>/dev/null | awk '{print $NF}' || true
}

r2_rm() {
  local key="$1"
  if $DRY_RUN; then
    echo "  [dry-run] delete: ${key}"
    return
  fi
  aws s3 rm "s3://${R2_BUCKET}/${key}" \
    --endpoint-url "${R2_ENDPOINT}" \
    --profile "${R2_PROFILE}" \
    --quiet
}

# =====================================================================
# Year-rollover detection (the only boundary this uploader still governs)
# =====================================================================

detect_boundaries() {
  # List existing dated monthly files (exclude 00-latest) and find the newest year.
  # If it differs from the release year, we archive the prior year before uploading.
  EXISTING_MONTHLY_FILES=()
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    [[ "$f" == *"00-latest"* ]] && continue
    [[ "$f" =~ ^clinvar-gkm_[0-9]{4}-[0-9]{2}\.json\.gz$ ]] || continue
    EXISTING_MONTHLY_FILES+=("$f")
  done < <(r2_ls "datasets/clinvar-gkm_")

  IS_NEW_YEAR=false
  PREV_YEAR=""

  local newest=""
  for f in "${EXISTING_MONTHLY_FILES[@]}"; do
    # clinvar-gkm_2026-06.json.gz -> newest lexical filename == newest year-month
    if [[ -z "$newest" || "$f" > "$newest" ]]; then
      newest="$f"
    fi
  done

  if [[ -n "$newest" ]]; then
    local date_part="${newest#clinvar-gkm_}"   # 2026-06.json.gz
    PREV_YEAR="${date_part:0:4}"               # 2026
    if [[ "$YEAR" != "$PREV_YEAR" ]]; then
      IS_NEW_YEAR=true
    fi
  fi
}

# =====================================================================
# Archive operations
# =====================================================================

archive_yearly() {
  # Move dated monthly files from datasets/ to archives/{prev_year}/.
  # LATEST_MONTHLY is retained; it gets overwritten by the new upload below.
  echo "--- Year rollover: archiving ${PREV_YEAR} monthly files to archives/${PREV_YEAR}/ ---"

  local monthly_files=()
  while IFS= read -r f; do
    [[ -n "$f" ]] && monthly_files+=("$f")
  done < <(r2_ls "datasets/clinvar-gkm_" | grep -v "00-latest" || true)

  for f in "${monthly_files[@]}"; do
    echo "  Moving datasets/${f} -> archives/${PREV_YEAR}/${f}"
    r2_copy "datasets/${f}" "archives/${PREV_YEAR}/${f}"
    r2_rm "datasets/${f}"
  done
}

archive_parquet_yearly() {
  # Move dated Parquet month sets (datasets/parquet/{YYYY-MM}/) from the prior year to
  # archives/{prev_year}/parquet/{YYYY-MM}/. Mirrors archive_yearly for the JSON bundles.
  # datasets/parquet/00-latest/ is retained; the new upload refreshes it below.
  echo "--- Year rollover: archiving ${PREV_YEAR} Parquet months to archives/${PREV_YEAR}/parquet/ ---"

  local month_dirs=()
  while IFS= read -r d; do
    d="${d%/}"
    [[ -z "$d" ]] && continue
    [[ "$d" == "00-latest" ]] && continue
    [[ "$d" =~ ^[0-9]{4}-[0-9]{2}$ ]] || continue
    month_dirs+=("$d")
  done < <(r2_ls "datasets/parquet/")

  for md in "${month_dirs[@]}"; do
    echo "  Moving datasets/parquet/${md}/ -> archives/${PREV_YEAR}/parquet/${md}/"
    # Per-file server-side copy+delete (a "move"); r2_copy picks the size-appropriate
    # method. A recursive `aws s3 mv` can't (no single --copy-props mode works for R2's
    # mixed object sizes). r2_copy/r2_rm both honor DRY_RUN.
    while IFS= read -r fn; do
      [[ -z "$fn" ]] && continue
      r2_copy "datasets/parquet/${md}/${fn}" "archives/${PREV_YEAR}/parquet/${md}/${fn}"
      r2_rm "datasets/parquet/${md}/${fn}"
    done < <(r2_ls "datasets/parquet/${md}/")
  done
}

upload_parquet() {
  local parquet_dir="$1"
  if [[ -z "$parquet_dir" || ! -d "$parquet_dir" ]]; then
    echo "  (no Parquet dir found, skipping)"
    return
  fi

  local month_prefix="datasets/parquet/${YEAR}-${MM}"
  local latest_prefix="datasets/parquet/00-latest"

  echo "--- Uploading Parquet section files -> ${month_prefix}/ ---"
  local uploaded=0
  for parquet_file in "${parquet_dir}"/*.parquet; do
    [[ -f "$parquet_file" ]] || continue
    local section
    section="$(basename "${parquet_file}" .parquet)"
    echo "  ${month_prefix}/${section}.parquet"
    r2_upload \
      "${parquet_file}" \
      "${month_prefix}/${section}.parquet" \
      "application/vnd.apache.parquet"
    (( uploaded++ )) || true
  done
  echo "  ${uploaded} Parquet files uploaded to ${month_prefix}/."

  # Refresh datasets/parquet/00-latest/ as a server-side copy of this month's set.
  # Wipe first: a section can drop out release-to-release (e.g. the proposition split
  # renamed sections), and without a wipe a stale prior section would linger in
  # 00-latest/ and misrepresent the newest full. Same idiom as the delta uploader.
  echo "--- Refreshing ${latest_prefix}/ ---"
  if $DRY_RUN; then
    echo "  [dry-run] clear ${latest_prefix}/ then copy each ${month_prefix}/<section> -> ${latest_prefix}/"
  else
    aws s3 rm "s3://${R2_BUCKET}/${latest_prefix}/" --recursive \
      --endpoint-url "${R2_ENDPOINT}" --profile "${R2_PROFILE}" --quiet 2>/dev/null || true
    # Per-file server-side copy (r2_copy picks the size-appropriate method); a recursive
    # `aws s3 cp` can't: it needs one --copy-props mode that R2 lacks for mixed sizes.
    for parquet_file in "${parquet_dir}"/*.parquet; do
      [[ -f "$parquet_file" ]] || continue
      local sect
      sect="$(basename "${parquet_file}" .parquet)"
      r2_copy "${month_prefix}/${sect}.parquet" "${latest_prefix}/${sect}.parquet"
    done
  fi
  echo "  ${latest_prefix}/ refreshed."
}

publish_monthly() {
  # Upload the bundle ONCE to the monthly slot, then server-side copy it to the
  # 00-latest pointer (no second multi-GB local upload). r2_copy uses --copy-props
  # none so R2's missing GetObjectTagging doesn't fail the copy.
  echo "--- Publishing monthly FULL ---"
  echo "  Monthly:  datasets/${MONTHLY_FILE}"
  r2_upload "${BUNDLE_FILE}" "datasets/${MONTHLY_FILE}"
  echo "  Latest:   datasets/${LATEST_MONTHLY} (server-side copy from monthly)"
  r2_copy "datasets/${MONTHLY_FILE}" "datasets/${LATEST_MONTHLY}"
}

# =====================================================================
# Main
# =====================================================================

echo "=== ClinVar-GKM Monthly FULL Upload ==="
echo "  Release date:  ${EXPORT_DATE}"
echo "  Version:       ${DATASET_VERSION}"
echo "  Monthly file:  ${MONTHLY_FILE}"
if $DRY_RUN; then
  echo "  Mode:          DRY RUN"
fi
echo ""

# --- Check bundle file ---
echo "Checking bundle: ${BUNDLE_FILE}"
if ! $DRY_RUN && [[ ! -f "${BUNDLE_FILE}" ]]; then
  echo "ERROR: Bundle file not found at ${BUNDLE_FILE}"
  echo "  Run export-gkm-dicts.sh and assemble-gkm-dicts.py first."
  exit 1
fi

# --- Detect year rollover (archive prior-year monthlies before publishing) ---
echo ""
echo "Detecting year rollover..."
detect_boundaries
echo "  New year:  ${IS_NEW_YEAR}"
echo ""

if $IS_NEW_YEAR; then
  archive_yearly
  archive_parquet_yearly
  echo ""
fi

# --- Publish the monthly full (unconditional) ---
publish_monthly
echo ""

# --- Upload Parquet files (if generated) ---
if [[ -n "${PARQUET_DIR}" ]]; then
  upload_parquet "${PARQUET_DIR}"
  echo ""
fi

# --- Upload README.txt ---
README_SRC="${SCRIPT_DIR}/r2-readme.txt"
if [[ -f "${README_SRC}" ]]; then
  echo "Uploading README.txt"
  r2_upload "${README_SRC}" "README.txt" "text/plain"
  echo ""
fi

# --- Regenerate index.json (shared generator) ---
INDEX_ARGS=()
$DRY_RUN && INDEX_ARGS+=("--dry-run")
"${SCRIPT_DIR}/generate-r2-index.sh" "${INDEX_ARGS[@]}"

# --- Summary ---
echo ""
echo "=== Upload Complete ==="
echo "  Monthly: ${R2_PUBLIC_URL}/datasets/${MONTHLY_FILE}"
echo "  Latest:  ${R2_PUBLIC_URL}/datasets/${LATEST_MONTHLY}"
if [[ -n "${PARQUET_DIR}" && -d "${PARQUET_DIR}" ]]; then
  echo "  Parquet: ${R2_PUBLIC_URL}/datasets/parquet/${YEAR}-${MM}/ (+ 00-latest/)"
fi
echo "  Index:   ${R2_PUBLIC_URL}/index.json"
